spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.24.2.55:3306/test
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.hnust.pojo
